#!/bin/bash
set -e

mysql -u root -p"$MYSQL_ROOT_PASSWORD" -P 5432 <<-EOSQL
    CREATE DATABASE IF NOT EXISTS tenant1_db;
    USE tenant1_db;
    CREATE TABLE IF NOT EXISTS users (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE);

    CREATE DATABASE IF NOT EXISTS tenant2_db;
    USE tenant2_db;
    CREATE TABLE IF NOT EXISTS users (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE);

    CREATE DATABASE IF NOT EXISTS tenant3_db;
    USE tenant3_db;
    CREATE TABLE IF NOT EXISTS users (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE);
EOSQL
